In [1]:
import pandas as pd
import numpy as np
import datetime
import os
import psycopg2
from sqlalchemy import create_engine
from decimal import Decimal

In [21]:
stores_df = pd.read_csv('datasets/Stores.csv')

In [ ]:
stores_df

In [ ]:
stores_df.info()

In [ ]:
stores_df.describe()

In [ ]:
stores_df[['Country','State','Open Date']].describe()

In [ ]:
stores_df.isna().sum()

In [ ]:
stores_df[stores_df['Square Meters'].isna()]

In [ ]:
stores_df['Open Date'].unique()

In [22]:
stores_df['Formatted Open Date'] = pd.to_datetime(stores_df['Open Date'], format='%m/%d/%Y')
stores_df['Formatted Open Date']

0    2008-01-01
1    2008-01-12
2    2012-01-07
3    2010-01-01
4    2015-12-09
        ...    
62   2008-03-06
63   2010-01-01
64   2012-01-01
65   2014-01-01
66   2010-01-01
Name: Formatted Open Date, Length: 67, dtype: datetime64[ns]

In [24]:
stores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   StoreKey             67 non-null     int64         
 1   Country              67 non-null     object        
 2   State                67 non-null     object        
 3   Square Meters        66 non-null     float64       
 4   Open Date            67 non-null     object        
 5   Formatted Open Date  67 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 3.3+ KB


In [16]:
def get_connection():

    user=os.environ['PG_USER']
    password=os.environ['PG_PASSWORD']
    host=os.environ['PG_HOST']
    port=os.environ['PG_PORT']
    database=os.environ['PG_DBNAME']
    
    conn_string = f'postgresql://{user}:{password}@{host}:{port}/{database}'
    db = create_engine(conn_string)
    
    return db.connect()


In [ ]:
#create_sql = create table cp2_stores(store_key INT, country VARCHAR(255) NOT NULL, country_state VARCHAR(255) NOT NULL, sq_meters DECIMAL, open_date DATE NOT NULL, PRIMARY KEY(store_key))

stores_df[['StoreKey','Country','State','Square Meters','Formatted Open Date']].to_sql('cp2_stores', get_connection(), if_exists='replace', index=False)

connection.close()

In [2]:
products_df = pd.read_csv('datasets/Products.csv')

In [10]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   ProductKey      2517 non-null   int64 
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64 
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64 
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB


In [12]:
products_df.duplicated().unique()

array([False])

In [18]:
len(products_df['ProductKey'].unique())

2517

In [19]:
products_df['CategoryKey'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
products_df['SubcategoryKey'].unique()

array([101, 104, 106, 201, 202, 203, 205, 301, 303, 304, 305, 306, 308,
       401, 402, 405, 406, 501, 503, 504, 602, 701, 702, 801, 802, 803,
       804, 805, 806, 807, 808, 505])

In [37]:
products_df['Unit Cost USD'].str.strip()

0        $6.62
1        $6.62
2        $7.40
3       $11.00
4       $11.00
         ...  
2512    $43.07
2513    $43.07
2514     $1.71
2515     $1.71
2516     $1.71
Name: Unit Cost USD, Length: 2517, dtype: object

In [27]:
products_df['Unit Cost USD'].str.startswith('$').sum()

np.int64(2517)

In [ ]:
#TODO: Unit Cost USD: Remove $ and trim the spaces beore storing as decimal

In [38]:
products_df['Unit Cost USD'].unique()

array(['$6.62 ', '$7.40 ', '$11.00 ', '$30.58 ', '$35.72 ', '$50.56 ',
       '$61.62 ', '$91.93 ', '$84.49 ', '$48.92 ', '$99.14 ', '$106.69 ',
       '$76.45 ', '$91.95 ', '$98.07 ', '$79.53 ', '$83.24 ', '$13.10 ',
       '$22.05 ', '$17.45 ', '$18.65 ', '$45.98 ', '$49.69 ', '$34.36 ',
       '$55.18 ', '$52.88 ', '$61.16 ', '$82.83 ', '$86.67 ', '$61.17 ',
       '$128.76 ', '$73.11 ', '$101.97 ', '$160.93 ', '$229.93 ',
       '$152.94 ', '$960.82 ', '$392.60 ', '$216.12 ', '$505.85 ',
       '$527.53 ', '$389.26 ', '$54.72 ', '$35.18 ', '$59.32 ', '$50.13 ',
       '$45.53 ', '$55.99 ', '$45.83 ', '$43.04 ', '$53.76 ', '$58.36 ',
       '$29.01 ', '$33.65 ', '$275.46 ', '$321.44 ', '$152.44 ',
       '$293.85 ', '$137.60 ', '$152.90 ', '$261.66 ', '$252.47 ',
       '$316.85 ', '$264.72 ', '$367.43 ', '$266.26 ', '$167.73 ',
       '$294.54 ', '$208.52 ', '$197.28 ', '$224.87 ', '$155.89 ',
       '$183.49 ', '$101.46 ', '$243.27 ', '$244.72 ', '$183.54 ',
       '$229.47 ', '$1

In [46]:
products_df['Brand'].str.len().unique()

array([ 7, 20, 17, 15, 16,  8,  9, 13])

In [47]:
products_df['Color'].str.len().unique()

array([ 6,  4,  5,  3, 11])

In [4]:
for x in ['Unit Price USD', 'Unit Cost USD']:
    products_df['t' + x] = products_df[x].apply(lambda x: x[1:].strip().replace(',','')).astype(float)

In [5]:
products_df

ProductKey                                   Product Name    Brand  \
0              1            Contoso 512MB MP3 Player E51 Silver  Contoso   
1              2              Contoso 512MB MP3 Player E51 Blue  Contoso   
2              3               Contoso 1G MP3 Player E100 White  Contoso   
3              4              Contoso 2G MP3 Player E200 Silver  Contoso   
4              5                 Contoso 2G MP3 Player E200 Red  Contoso   
...          ...                                            ...      ...   
2512        2513    Contoso Bluetooth Active Headphones L15 Red  Contoso   
2513        2514  Contoso Bluetooth Active Headphones L15 White  Contoso   
2514        2515             Contoso In-Line Coupler E180 White  Contoso   
2515        2516             Contoso In-Line Coupler E180 Black  Contoso   
2516        2517            Contoso In-Line Coupler E180 Silver  Contoso   

       Color Unit Cost USD Unit Price USD  SubcategoryKey  \
0     Silver        $6.62         $12.99              101   
1       Blue        $6.62         $12.99              101   
2      White        $7.40         $14.52              101   
3     Silver       $11.00         $21.57              101   
4        Red       $11.00         $21.57              101   
...      ...           ...            ...             ...   
2512     Red       $43.07        $129.99              505   
2513   White       $43.07        $129.99              505   
2514   White        $1.71          $3.35              505   
2515   Black        $1.71          $3.35              505   
2516  Silver        $1.71          $3.35              505   

                  Subcategory  CategoryKey     Category  tUnit Price USD  \
0                     MP4&MP3            1        Audio            12.99   
1                     MP4&MP3            1        Audio            12.99   
2                     MP4&MP3            1        Audio            14.52   
3                     MP4&MP3            1        Audio            21.57   
4                     MP4&MP3            1        Audio            21.57   
...                       ...          ...          ...              ...   
2512  Cell phones Accessories            5  Cell phones           129.99   
2513  Cell phones Accessories            5  Cell phones           129.99   
2514  Cell phones Accessories            5  Cell phones             3.35   
2515  Cell phones Accessories            5  Cell phones             3.35   
2516  Cell phones Accessories            5  Cell phones             3.35   

      tUnit Cost USD  
0               6.62  
1               6.62  
2               7.40  
3              11.00  
4              11.00  
...              ...  
2512           43.07  
2513           43.07  
2514            1.71  
2515            1.71  
2516            1.71  

[2517 rows x 12 columns]

In [6]:
products_df.isna().sum()

ProductKey         0
Product Name       0
Brand              0
Color              0
Unit Cost USD      0
Unit Price USD     0
SubcategoryKey     0
Subcategory        0
CategoryKey        0
Category           0
tUnit Price USD    0
tUnit Cost USD     0
dtype: int64

In [10]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ProductKey       2517 non-null   int64  
 1   Product Name     2517 non-null   object 
 2   Brand            2517 non-null   object 
 3   Color            2517 non-null   object 
 4   Unit Cost USD    2517 non-null   object 
 5   Unit Price USD   2517 non-null   object 
 6   SubcategoryKey   2517 non-null   int64  
 7   Subcategory      2517 non-null   object 
 8   CategoryKey      2517 non-null   int64  
 9   Category         2517 non-null   object 
 10  tUnit Price USD  2517 non-null   float64
 11  tUnit Cost USD   2517 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 236.1+ KB


In [15]:
#create table cp2_products(product_key INT, product_name VARCHAR(255) NOT NULL, brand VARCHAR(255) NOT NULL, color varchar(255) not null, subcategory_key integer not null, subcategory varchar(255) not null, category_key integer not null, category varchar(255) not null, unit_price DECIMAL not null, unit_cost decimal not null, PRIMARY KEY(product_key))

len(products_df['ProductKey'].unique())

2517

In [19]:

products_df[['ProductKey','Product Name','Brand','Color','SubcategoryKey','Subcategory','CategoryKey','Category','tUnit Price USD','tUnit Cost USD']].to_sql('cp2_products', get_connection(), if_exists='replace', index=False)


517